# PostgreSQL LOCAL
spring.datasource.url=jdbc:postgresql://localhost:5432/organizacao_estudos
spring.datasource.username=postgres
spring.datasource.password=602027@

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.h2.console.enabled=false
server.port=9090
